apiVersion: apps/v1
kind: Deployment
metadata:
  name: kserve-models-web-app
  namespace: kserve
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: kserve-models-web-app
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kserve-models-web-app
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "node-role.kubernetes.io/master"
                operator: In
                values: [""]
      containers:
      - image: kserve/models-web-app:latest
        imagePullPolicy: Always
        name: kserve-models-web-app
        envFrom:
          - configMapRef:
              name: kserve-models-web-app-config
        ports:
        - containerPort: 5000
      serviceAccountName: kserve-models-web-app
