apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-deployer-deployment
  labels:
    app: cache-deployer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache-deployer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cache-deployer
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: "node-role.kubernetes.io/master"
                    operator: In
                    values: [""]
              weight: 1
      containers:
      - name: main
        image: gcr.io/ml-pipeline/cache-deployer:dummy
        imagePullPolicy: Always
        env:
        - name: NAMESPACE_TO_WATCH
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      serviceAccountName: kubeflow-pipelines-cache-deployer-sa
      restartPolicy: Always
