apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-viewer-crd
spec:
  template:
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "node-role.kubernetes.io/master"
                operator: In
                values: [""]
      containers:
      - name: ml-pipeline-viewer-crd
        env:
        - name: NAMESPACE
          value: '' # Empty namespace let viewer controller watch all namespaces
          valueFrom: null
